spring:
  application:
    name: mirchi-eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5



      
management:
  endpoints:
    web:
      exposure:
        include: "*"
